language: python
python:
  - "2.7"

before_install:
  - wget https://github.com/coreos/etcd/releases/download/v2.0.11/etcd-v2.0.11-linux-amd64.tar.gz
  - tar -zxvf etcd-v2.0.11-linux-amd64.tar.gz
  - ./etcd-v2.0.11-linux-amd64/etcd &
  - sleep 2

install:
  - pip install pytz
  - pip install coveralls

services:
  - redis-server
  - memcached

# command to run tests
script:
  coverage run --source=sherlock setup.py test

after_success:
  coveralls
